### ISSUE TITLE
the app does not recognize the cfw where it is running

### ISSUE THREAD

**Issue by cronolinkoriginal** [HamletDuFromage/switch-cheats-updater#11]
i'm running atm, and the app indicates that i'm on reinx

therefore the content of the txt file downloads are misplaced.

if possible the program allows you to choose which CFW you are starting and thus avoid this type of inconvenience

if you need a screen to show them I can upload it

thank you very much for your support

**Comment by HamletDuFromage** [comment]
Are you absolutely sure you're using atmosphere and not ReiNX? Because that really shouldn't be happening considering for ReiNX CFW to be detected by the app, the "rnx" service has to be running. 
The problem with adding an option to select your CFW is that for 99% of the userbase, it's bloat and makes things harder.

Are the cheats extracted in `/ReiNX/contents`? If so that's weird but you should be able to move them to `atmosphere/contents`

**Comment by cronolinkoriginal** [comment]
If you like I can pass you some screenshots

Now I use a pack and I also use the shared emunand. This pack contains the three CFW: ATM, REINX, SXOS.

That's why I suggest you to enable an option that allows you to choose which CFW you use and this way you won't make mistakes.

For users who use pack

The pack I use is called the retrogamer 74 PRO retroreload

Thank you, my friend.

If you want the screens as evidence I will upload them

**Comment by HamletDuFromage** [comment]
Ah ok. So when you ran the homebrew, you were using ReiNX but didn't know it. 
I really don't understand why you'd need to run three CFWs in the first place, but I won't add an option that caters to that specific need since that'd be annoying for everyone else. I suggest you stick to a specific CFW when using cheats.
