### ISSUE TITLE
Suggestion (Update Application from Github) + Problem

### ISSUE THREAD

**Issue by Ghostk0** [HamletDuFromage/switch-cheats-updater#6]
Hello.

Would it be possible to integrate version updates into the application?

Example: I have cheats-updater version 1.1.7, and I would like to update the application to version 1.2.0. The problem is that I have to go back to github, download it and install it manually on the SD card.

Why don't I integrate this into the program by downloading from github?

I would like to take advantage of this issue to report a problem: when I download my cheats, all goes very well, then I press the "+" button to exit the program, and then I have a WHITE screen, I have to restart the switch.

**Comment by HamletDuFromage** [comment]
I suggest you use the hb appstore to get updates on your homebrew applications. You can also use a ftp client like ftpd or sys-ftpd-light to transfer files without taking your SD card out. I believe latest hetake is recognized as a mass storage device when connected to a computer

As for your problem, does it happen on the latest version? There have been a few bug fixes since 1.1.7

**Comment by Ghostk0** [comment]
Thank you for that answer.

I have just updated the application to 1.2.0, and there is no longer this white screen problem.

**Comment by HamletDuFromage** [comment]
De rien chef
